Repository alkemyTech/OT246-Node, pull requests merged in 2022-07, with the labels that each got.

#14 [ROLES] fix wrong variable name
  database/models/role.js
Labels: fix

#13 [ENDPOINT] GET /organization/public OT246-23
  controllers/organizations.js
  routes/index.js
  routes/organizations.js
  services/organizations.js
Labels: endpoint

#17 [ENDPOINT] GET /slides/:id OT246-58
  controllers/slides.js
  routes/index.js
  routes/slides.js
  services/slides.js
Labels: endpoint

#18 [SLIDES] create migration and slides model's OT246-29
  database/migrations/20220720172105-create-slide.js
  database/models/organization.js
  database/models/slide.js
Labels: models

#15 [MEMBERS] created model, migration and base controller of Members
  controllers/members.js
  database/migrations/20220720141059-create-member.js
  database/models/member.js
Labels: models

#21 [ENDPOINT] GET /organization/public: fix controller and service methods OT246-23
  controllers/organizations.js
  services/organizations.js
Labels: fix

#20 [ENDPOINT] DELETE /users/:id
  controllers/users.js
  database/models/user.js
  routes/index.js
  routes/users.js
  services/users.js
Labels: endpoint

#25 [Template] Welcome email template
  mailTemplates/welcome.html
Labels: enhancement

#22 [ENDPOINT] GET /categories/public OT246-41 (fixed names)
  controllers/categories.js
  services/categories.js
Labels: fix

#26 [ENDPOINT] POST /auth/register OT246-24
  controllers/users.js
  database/models/user.js
  middlewares/validations.js
  package.json
  routes/auth.js
  routes/index.js
  schemas/register.js
  services/users.js
Labels: endpoint

#27 [FEATURE] Add JWT logic - OT246-32
  middlewares/jwt.js
  package.json
Labels: enhancement

#12 [TESTIMONIALS] Testimonials model and migrations OT246-20
  controllers/testimonials.js
  database/migrations/20220719214208-create-testimonial.js
  database/models/testimonial.js
Labels: models

#24 [SERVICE] Integrate email sending OT246 28
  .env.example
  package.json
  services/sendMail.js
Labels: mail

#29 [Middleware] Ownership middleware
  middlewares/ownership.js
Labels: enhancement, middleware

#28 [MIDDLEWARE] Middleware for Authenticated Users
  middlewares/authUser.js
Labels: middleware

#31 [ENDPOINT] Update User Endpoint - OT246-35
  controllers/users.js
  routes/users.js
  services/users.js
Labels: endpoint

#30 [SERVICE] Welcome email sending OT246-31
  controllers/users.js
  services/sendMail.js
Labels: mail

#34 [ENDPOINT] GET /categories/:id OT246-42
  controllers/categories.js
  routes/categories.js
  services/categories.js
Labels: endpoint

#37 [ENDPOINT] Endpoint Creation Categories - OT246-43
  controllers/categories.js
  routes/categories.js
  schemas/categories.js
  services/categories.js
Labels: endpoint

#35 [Service] Support for Amazon S3 file management
  .env.example
  package.json
  services/amazonS3.js
Labels: enhancement

#36 [ENDPOINT] GET /auth/me OT246 37
  controllers/users.js
  routes/auth.js
  services/users.js
Labels: endpoint

#39 [ENDPOINT] PUT /categories/:id OT246-44
  controllers/categories.js
  routes/categories.js
  schemas/categories.js
  services/categories.js
Labels: endpoint

#40 [ENDPOINT] Endpoint Detail News OT246-46
  controllers/news.js
  routes/index.js
  routes/news.js
  services/news.js
Labels: endpoint

#38 [FIX] Created a FIX in the Schema of organization
  schemas/organization.js
Labels: fix

#43 [FIX] Create a S3 CLIENT OT246-39
  .env.example
  package.json
  services/amazonS3.js
Labels: fix

#45 [Endpoint] Delete category endpoint
  controllers/categories.js
  routes/categories.js
  services/categories.js
Labels: endpoint

#41 [ENDPOINT] POST /news OT246 47
  controllers/news.js
  database/migrations/20220720171428-create-new.js
  database/models/new.js
  routes/news.js
  schemas/news.js
  services/news.js
Labels: endpoint

#44 [MODEL] create model & migration of Activities OT246 49
  database/migrations/20220727124822-create-activity.js
  database/models/activity.js
Labels: models

#47 [Endpoint] Create Activities
  controllers/activities.js
  routes/activities.js
  routes/index.js
  schemas/activities.js
  services/activities.js
Labels: endpoint

#23 [MIDDLEWARE] - Verification Admin user
  middlewares/adminVerification.js
Labels: middleware

#46 [ENDPOINT] Delete News - OT 246-50
  controllers/news.js
  routes/news.js
  services/news.js
Labels: endpoint

#48 [ENDPOINT] PUT /news/:id OT246-48
  controllers/news.js
  routes/news.js
  schemas/news.js
  services/news.js
Labels: endpoint

#51 [SEED] Create seeders to save existing Activities of the ONG
  database/seeders/20220728005213-generate-activities.js
Labels: seed

#49 [Models] Contact model & migration
  database/migrations/20220727211550-create-contact.js
  database/models/contact.js
Labels: models

#53 [FIX] - Minor fix on middleware isUserAdmin
  middlewares/adminVerification.js
Labels: fix

#42 [SERVICE] service to upload images OT246-40
  .env.example
  services/amazonS3.js
  services/uploadFile.js
Labels: service

#57 [ENDPOINT] Endpoint to list contacts OT246-63
  controllers/contacts.js
  routes/contacts.js
  routes/index.js
  services/contacts.js
Labels: endpoint

#56 [Fix] Model & Migration of Contact Fixed
  database/migrations/20220727211550-create-contact.js
  database/models/contact.js
Labels: fix

#50 [Endpoint] List the Slides OT246-57
  controllers/slides.js
  routes/slides.js
  services/slides.js
Labels: endpoint

#54 [ENDPOINT] GET /users
  controllers/users.js
  routes/users.js
  services/users.js
Labels: endpoint

#58 [ENDPOINT] Endpoint Update Slides
  controllers/slides.js
  routes/slides.js
  services/slides.js
Labels: endpoint, service, controller

#59 [Endpoint] Eliminación Slides
  controllers/slides.js
  routes/slides.js
  services/slides.js
Labels: endpoint

#60 [SERVICE] Send contact email OT246-64
  controllers/contacts.js
  routes/contacts.js
  routes/index.js
  schemas/contacts.js
  services/contacts.js
  services/sendMail.js
Labels: service

#52 [SERVICE] Token in register OT246 51
  controllers/users.js
  services/users.js
Labels: service

#65 [FIX]
  middlewares/adminVerification.js
  middlewares/authUser.js
  services/users.js
Labels: fix
