Repository alkemyTech/OT246-Node, pull requests merged in 2022-08, with the labels that each got.

#62 [MODEL & MIGRATION] Create Migration and Testimonials Model OT246-68
  database/migrations/20220729163130-create-testimonial.js
  database/models/testimonial.js
Labels: models

#63 [MODELS] Add contact fields to organizations OT246-66
  database/migrations/20220729211567-create-organization.js
  database/models/organization.js
Labels: models

#55 [ENDPOINT] PUT /activities/:id
  controllers/activities.js
  routes/activities.js
  schemas/activities.js
  services/activities.js
Labels: endpoint, service, controller

#69 [ENDPOINT] Creation Testimonials OT246-69
  controllers/testimonials.js
  routes/index.js
  routes/testimonials.js
  schemas/testimonials.js
  services/testimonials.js
Labels: endpoint, service, controller

#68 [ENDPOINT] Endpoint Update Testimonials OT246-70
  controllers/testimonials.js
  routes/testimonials.js
  services/testimonials.js
Labels: endpoint, service, controller

#64 [Organizations] Modified endpoint organizations with new fields
  schemas/organization.js
  services/organizations.js
Labels: enhancement

#67 [ENDPOINT] POST/slide OT246-59
  controllers/slides.js
  routes/slides.js
  services/slides.js
  services/uploadFile.js
Labels: endpoint

#74 [FIX] Standarize Responses
  controllers/activities.js
  controllers/categories.js
  controllers/contacts.js
  controllers/news.js
  controllers/organizations.js
  controllers/slides.js
  controllers/testimonials.js
  controllers/users.js
  routes/news.js
  routes/organizations.js
  services/news.js
  services/sendMail.js
  services/users.js
Labels: fix

#75 [FIX] Correct migrations order
  database/migrations/20220719205910-create-organization.js
Labels: fix

#71 [MEMBERS] Remove fields from Members
  database/migrations/20220720141059-create-member.js
  database/models/member.js
Labels: models

#72 [Endpoint] Testimonials delete endpoint
  controllers/testimonials.js
  routes/testimonials.js
  services/testimonials.js
Labels: endpoint

#70 [ENDPOINT] Creation Members
  controllers/members.js
  routes/index.js
  routes/members.js
  schemas/members.js
  services/members.js
Labels: endpoint, service, controller

#76 [REFACTOR] Authentication Cycle 🐛
  controllers/users.js
  middlewares/adminVerification.js
  middlewares/auth.js
  middlewares/authUser.js
  middlewares/authUserAdmin.js
  middlewares/jwt.js
  middlewares/ownership.js
  routes/activities.js
  routes/backoffice.js
  routes/contacts.js
  routes/members.js
  routes/slides.js
  routes/testimonials.js
  routes/users.js
  services/users.js
Labels: fix

#78 [ENDPOINT] Delete Members OT246-75
  controllers/members.js
  middlewares/authUserAdmin.js
  routes/activities.js
  routes/backoffice.js
  routes/contacts.js
  routes/members.js
  routes/slides.js
  routes/testimonials.js
  routes/users.js
  services/members.js
Labels: endpoint, service, controller

#77 [FIX] Create slides
  app.js
  controllers/slides.js
  package.json
  services/uploadFile.js
Labels: bug

#80 [ENDPOINT] PUT /members/:id
  controllers/members.js
  routes/members.js
  services/members.js
Labels: endpoint

#83 [FIX] SEED ACTIVITIES OT246-54
  database/seeders/20220728005213-generate-activities.js
Labels: fix

#81 [SEED] User's seeder OT246-77
  README.md
  database/seeders/20220803140350-users-users.js
Labels: seed

#85 [Models] Comments Model & Migration
  database/migrations/20220804004333-create-comment.js
  database/models/comment.js
  database/models/new.js
  database/models/user.js
Labels: models

#84 [ENDPOINT] Endpoint to list Comments OT246-80
  controllers/comments.js
  routes/comments.js
  routes/index.js
  services/comments.js
Labels: endpoint, service, controller

#82 [ENDPOINT] - GET /members OT246-73
  controllers/members.js
  routes/members.js
  services/members.js
Labels: endpoint

#87 [ENDPOINT] POST /comments OT246-81
  controllers/comments.js
  routes/comments.js
  routes/index.js
  schemas/comments.js
  services/comments.js
Labels: endpoint

#91 [ENDPOINT] - PUT /comments/:id
  controllers/comments.js
  routes/comments.js
  schemas/comments.js
  services/comments.js
Labels: endpoint

#88 [Endpoint] Comments by news
  controllers/comments.js
  routes/news.js
  services/comments.js
Labels: endpoint

#93 [ENDPOINT] GET /testimonials OT246-88
  controllers/testimonials.js
  routes/testimonials.js
  services/testimonials.js
Labels: endpoint

#97 [Pagination] Members pagination
  controllers/members.js
  services/members.js
Labels: Pagination

#96 [PAGINATION] Add Pagination to Categories
  controllers/categories.js
  routes/categories.js
  services/categories.js
Labels: Pagination

#98 [TEST] Test: Endpoints /members - OT296
  test/members.test.js
Labels: test

#99 [DOCUMENTATION] /auth
  routes/auth.js
  routes/index.js
Labels: documentation

#100 [TEST] Test: Endpoints /organization - OT297
  test/organizations.test.js
Labels: test

#101 [TEST] Endpoints /activities
  test/activities.test.js
Labels: test

#103 [TEST] Test: Endpoints /news OT246-298
  test/news.test.js
Labels: test

#105 [TEST] Endpoints /contact
  test/contacts.test.js
Labels: test

#106 [Documentation] Members endpoints
  routes/members.js
Labels: documentation

#104 [DOCUMENTATION] Categories OT246-90
  docs/categories.js
Labels: documentation

#108 [Test] Endpoints /users
  test/users.test.js
Labels: test

#107 [DOCUMENTATION] - Add Documentation to What's New OT246-91
  routes/news.js
Labels: documentation

#109 Fixed tests
  test/activities.test.js
  test/contacts.test.js
  test/members.test.js
  test/users.test.js
Labels: fix

#110 [FIX] Added middleware AuthUser to endpoint user
  middlewares/ownership.js
  routes/users.js
Labels: fix

#111 [FIX] Fixed validation schema of organization
  schemas/organization.js
Labels: fix
